using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//Find the sum of all the even-valued terms in the sequence which do not exceed four million.

namespace Problem_2
{
    class Program
    {
        static void Main(string[] args)
        {
            List<int> fibonnacci = new List<int>{1, 2};
            int sum = 0;

            int highestNumber = 0;

            while (highestNumber <= 4000000)
            {
                fibonnacci.Add(fibonnacci[fibonnacci.Count - 1] + fibonnacci[fibonnacci.Count - 2]);
                highestNumber = fibonnacci[fibonnacci.Count - 1];
            }

            foreach (int i in fibonnacci)
            {
                if (i % 2 == 0)
                    sum += i;
            }

            Console.WriteLine(sum);
            Console.Read();
        }
    }
}
